---
- name: Install base package
  package:
    name:
    - yum-utils
    state: installed
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 3

- name: Set the latency-performance profile
  shell: tuned-adm profile latency-performance

- name: Set TCP keepalive
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }} "
    sysctl_set: yes
    state: present
    reload: yes
  loop:
  - item: net.ipv4.tcp_keepalive_time
    value: 60
  - item: net.ipv4.tcp_keepalive_probes
    value: 3
  - item: net.ipv4.tcp_keepalive_intvl
    value: 10

- name: Set network buffer
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }} "
    sysctl_set: yes
    state: present
    reload: yes
  loop:
  - item: net.core.rmem_max
    value: 16777216
  - item: net.core.wmem_max
    value: 16777216
  - item: net.core.rmem_default
    value: 16777216
  - item: net.core.wmem_default
    value: 16777216
  - item: net.core.optmem_max
    value: 40960
  - item: net.ipv4.tcp_rmem
    value: 4096 87380 16777216
  - item: net.ipv4.tcp_wmem
    value: 4096 65536 16777216

- name: Set swappiness
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }} "
    sysctl_set: yes
    state: present
    reload: yes
  loop:
  - item: vm.swappiness
    value: 1

- name: Set SSD settings
  include_tasks: ssd.yml
  loop: "{{ ssd_devices|default([]) }}"
  loop_control:
    loop_var: ssd_device


# set limits


