---
- block:
  - name: Setup firewall chain by direct
    shell: |
      if {{ 'true' if firewall_chain_direct_rule_state == 'present' else 'false' }} ; then
        if ! iptables-save | grep '^:{{ item.chain }}' ; then
          firewall-cmd --direct --add-chain {{ item.ipv }} {{ item.table }} {{ item.chain }} && echo changed;
        else
          echo skipped;
        fi
      else
        if firewall-cmd --direct --get-chains {{ item.ipv }} {{ item.table }} | grep '{{ item.chain }}' ; then
          firewall-cmd --direct --remove-chain {{ item.ipv }} {{ item.table }} {{ item.chain }} && echo changed;
        else
          echo skipped;
        fi
      fi
    args:
      executable: /bin/bash
    register: command_result
    changed_when: command_result.stdout_lines|length > 0 and command_result.stdout_lines[-1] == 'changed'
    loop: "{{ firewall_chain_direct_rule_list }}"

  - name: Setup firewall chain by direct --permanent
    shell: |
      if {{ 'true' if firewall_chain_direct_rule_state == 'present' else 'false' }} ; then
        if ! firewall-cmd --permanent --direct --get-chains {{ item.ipv }} {{ item.table }} | grep '{{ item.chain }}' ; then
          firewall-cmd --permanent --direct --add-chain {{ item.ipv }} {{ item.table }} {{ item.chain }} && echo changed;
        else
          echo skipped;
        fi
      else
        if firewall-cmd --permanent --direct --get-chains {{ item.ipv }} {{ item.table }} | grep '{{ item.chain }}' ; then
          firewall-cmd --permanent --direct --remove-chain {{ item.ipv }} {{ item.table }} {{ item.chain }} && echo changed;
        else
          echo skipped;
        fi
      fi
    args:
      executable: /bin/bash
    register: command_result
    changed_when: command_result.stdout_lines|length > 0 and command_result.stdout_lines[-1] == 'changed'
    when: firewall_chain_direct_rule_permanent|bool
    loop: "{{ firewall_chain_direct_rule_list }}"
    notify:
    - reload firewalld

  when: firewall_chain_direct_rule_state in [ 'present', 'absent' ]
