---
- block:
  # - set_fact:
  #     eos_components: "{{ containers.eos_proxy }}"

  - name: Setup container
    include_tasks: tasks/eos_container_setup.yml
    vars:
      components: "{{ containers.eos_proxy }}"
      config_base_directory: "{{ eos_proxy_config_base_directory }}"
      shipped_files: "{{ eos_proxy_shipped_files }}"
      generated_files: "{{ eos_proxy_generated_files }}"
      template_files: "{{ eos_proxy_template_files }}"
      config_files: "{{ eos_proxy_config_files }}"
      config_directories: "{{ eos_proxy_config_directories }}"
      persistent_volumes: "{{ eos_proxy_persistent_volumes }}"
      privileged_container: yes
      entrypoint: "/eos_proxy_setup.sh"
      command: ""

  # - name: Start service
  #   shell: docker exec -i {{ item.item.name }} /eos_proxy_setup.sh
  #   when: item.changed
  #   loop: "{{ container_start_results.results }}"

  when: containers is defined and containers.eos_proxy is defined
