---
- block:
  - name: Setup container
    include_tasks: tasks/container_setup.yml
    vars:
      components: "{{ containers.grafana_loki }}"
      config_base_directory: "{{ grafana_loki_config_base_directory }}"
      shipped_files: "{{ grafana_loki_shipped_files }}"
      generated_files: "{{ grafana_loki_generated_files }}"
      template_files: "{{ grafana_loki_template_files }}"
      config_files: "{{ grafana_loki_config_files }}"
      config_directories: "{{ grafana_loki_config_directories }}"
      persistent_volumes: "{{ grafana_loki_persistent_volumes }}"

  - name: Start container
    docker_container:
      name: "{{ item.name }}"
      image: "{{ item.image }}"
      state: started
      hostname: "{{ item.name }}.{{ item.domain }}"
      purge_networks: yes
      networks:
      - name: "{{ item.network }}"
        ipv4_address: "{{ item.ipv4_address }}"
        aliases: "{{ [ item.name ] + item.network_aliases|default([]) }}"
      volumes: "{{ container_volumes[item.name] }}"
      etc_hosts: "{{ item.etc_hosts|default(omit) }}"
      command: -config.file=/etc/loki/local-config.yaml
    register: container_start_results
    loop: "{{ container_infos }}"

  when: containers is defined and containers.grafana_loki is defined
