---
- block:
  # - set_fact:
  #     eos_components: "{{ containers.eos_mgm }}"

  - name: Setup container
    include_tasks: tasks/eos_container_setup.yml
    vars:
      components: "{{ containers.eos_mgm }}"
      config_base_directory: "{{ eos_mgm_config_base_directory }}"
      shipped_files: "{{ eos_mgm_shipped_files }}"
      generated_files: "{{ eos_mgm_generated_files }}"
      template_files: "{{ eos_mgm_template_files }}"
      config_files: "{{ eos_mgm_config_files }}"
      config_directories: "{{ eos_mgm_config_directories }}"
      persistent_volumes: "{{ eos_mgm_persistent_volumes }}"
      privileged_container: yes
      entrypoint: "/eos_mq_mgm_setup.sh"
      command: ""

  # - name: Start service mq
  #   shell: docker exec -i {{ item.item.name }} /eos_mq_setup.sh
  #   when: item.changed
  #   loop: "{{ container_start_results.results }}"

  # - name: Start service mgm
  #   shell: docker exec -i {{ item.item.name }} /eos_mgm_setup.sh
  #   when: item.changed
  #   loop: "{{ container_start_results.results }}"

  when: containers is defined and containers.eos_mgm is defined
