---
- block:
  - set_fact:
      eos_componets: "{{ containers.eos_mgm }}"

  - name: Setup container
    include_tasks: tasks/eos_container_setup.yml

  - name: Start service mq
    shell: docker exec -i {{ item.item.name }} /eos_mq_setup.sh
    when: item.changed
    loop: "{{ container_start_results.results }}"

  - name: Start service mgm
    shell: docker exec -i {{ item.item.name }} /eos_mgm_setup.sh
    when: item.changed
    loop: "{{ container_start_results.results }}"

  when: containers is defined and containers.eos_mgm is defined
