---
- name: Setup firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
    zone: internal
  loop: 
  - 50051/tcp
  - 1094/tcp
  - 1097/tcp
  - 8000/tcp
  - 1100/tcp
  when: containers.eos_mgm[0].network_mode is defined
  notify:
  - reload firewalld
- meta: flush_handlers

- block:
  - name: Setup container
    include_tasks: tasks/eos_container_setup.yml
    vars:
      components: "{{ containers.eos_mgm }}"
      config_base_directory: "{{ eos_mgm_config_base_directory }}"
      shipped_files: "{{ eos_mgm_shipped_files }}"
      generated_files: "{{ eos_mgm_generated_files }}"
      template_files: "{{ eos_mgm_template_files }}"
      config_files: "{{ eos_mgm_config_files }}"
      config_directories: "{{ eos_mgm_config_directories }}"
      persistent_volumes: "{{ eos_mgm_persistent_volumes }}"
      privileged_container: yes
      command:
      - mgm

  - set_fact:
      restart_notifies: >-
        {% set result = [] -%}
        {% for item in create_template_file_results.results + create_generated_file_results.results -%}
        {%   if item.changed and item.item[0].is_initialized -%}
        {{     result.append( item.item[0].name ) -}}
        {%   endif -%}
        {% endfor -%}
        {{ result|unique }}

  - name: Restart by config files
    shell: docker restart {{ item }}
    loop: "{{ restart_notifies|default([]) }}"

  when: containers is defined and containers.eos_mgm is defined
