---
- block:
  # - set_fact:
  #     eos_components: "{{ containers.eos_fst }}"

  - name: Setup container
    include_tasks: tasks/eos_container_setup.yml
    vars:
      components: "{{ containers.eos_fst }}"
      config_base_directory: "{{ eos_fst_config_base_directory }}"
      shipped_files: "{{ eos_fst_shipped_files }}"
      generated_files: "{{ eos_fst_generated_files }}"
      template_files: "{{ eos_fst_template_files }}"
      config_files: "{{ eos_fst_config_files }}"
      config_directories: "{{ eos_fst_config_directories }}"
      persistent_volumes: "{{ eos_fst_persistent_volumes }}"
      privileged_container: yes
      entrypoint: "/eos_fst_setup.sh"
      command: ""

  # - name: Start service
  #   shell: docker exec -i {{ item.item.name }} /eos_fst_setup.sh
  #   when: item.changed
  #   loop: "{{ container_start_results.results }}"

  when: containers is defined and containers.eos_fst is defined
