---
grafana_server_config_base_directory: /etc/grafana
grafana_server_shipped_files: []
# - { name: "", dest: "", force: false, is_volume: true }
grafana_server_generated_files: []
# - { name: "", dest: "", src: "", owner: "root", group: "root", mode: "0600", force: true, is_volume: true }
grafana_server_template_files:
# - { name: "", dest: "", src: "", owner: "root", group: "root", mode: "0600", force: false, is_volume: true }
- { name: "provisioning/datasources/loki.yaml", dest: "", src: "loki.yaml.j2", owner: "{{ grafana_uid }}", group: "{{ grafana_gid }}", mode: "0644", force: false, is_volume: false }
grafana_server_config_files: []
# - { name: "", dest: "", src: "", owner: "root", group: "root", mode: "0600", force: false, is_volume: true }
grafana_server_config_directories:
# - { name: "", dest: "", is_volume: true }
- { name: "provisioning", dest: "/etc/grafana/provisioning", is_volume: true }
- { name: "provisioning/dashboards", dest: "", is_volume: false }
- { name: "provisioning/datasources", dest: "", is_volume: false }
- { name: "provisioning/notifiers", dest: "", is_volume: false }
grafana_server_persistent_volumes:
# - { name: "", dest: "" }
- { name: "data", dest: "/var/lib/grafana" }
- { name: "log", dest: "/var/log/grafana" }

grafana_uid: "472"
grafana_gid: "472"
