- name: copy ssh public key
  hosts: all
  tasks:
  - authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
